### ISSUE TITLE
Virus

### ISSUE THREAD

**Issue by Ivoyko** [RikuKH3/unpkg_vita#1]
i prefer writte this here and not in Discord but in Windows 10... Defender says than u can open it because have virus or potentil malware.
I dont know if u know it and want fuck computers how that Silica with the virus vitamin dumps than did... or its new to you... but i dont think people want use ur tool if appear that.

**Comment by alpakeno** [comment]
don't trust windows defender\virus tools, also it's an open source
so you can compile it if you want to be 100% safe.

**Comment by RikuKH3** [comment]
It's clean:
https://www.virustotal.com/en/file/81746e3db8118321e36f2b57719abc29126c31b232fea9db4123496948e6dc55/analysis/1506100748/
